//! Hermetic byte-identity CI test (Phase 6).
//!
//! For each flag-combination cell, runs the `bismark2bedGraph_rs` binary on
//! the committed methylation-call fixtures and compares its **decompressed**
//! output (SPEC §1.1 D1) against the expected files under
//! `tests/fixtures/expected/<cell>/`. Those expected files were generated by
//! the **Perl `bismark2bedGraph` v0.25.1** (the independent producer) — see
//! `tests/fixtures/README.md` — so a match is a real byte-identity signal,
//! not a tautology.
//!
//! The fixtures deliberately exercise: argv-order chromosome ownership (MT
//! appears only on `CpG_OB`, which owns it, and — because `"CpG_OB" <
//! "CpG_OT"` — sorts FIRST), ASCII chr ordering (`1, 10, 2`), cross-strand
//! position merge, the `%.15g` percentage (`1/3`, `6/7`, …), `--cutoff`
//! filtering, `--CX` (CHG/CHH files included), the `--zero_based` plain file,
//! the `--ucsc` transform (`MT`→`chrM`, `chr` prefix), and a pipe-bearing
//! chromosome name (`GL000|1`: orders via `GL000_1`, outputs the original).

use std::fs;
use std::io::Read;
use std::path::{Path, PathBuf};

use assert_cmd::Command;
use flate2::read::GzDecoder;
use tempfile::TempDir;

/// The four committed input fixtures (default mode uses the two CpG files;
/// `--CX` additionally uses CHG/CHH).
const FIXTURE_FILES: &[&str] = &[
    "CpG_OT_s.txt",
    "CpG_OB_s.txt",
    "CHG_OT_s.txt",
    "CHH_OT_s.txt",
];

/// One produced output to check: the on-disk filename, whether it is gzipped
/// (and so must be decompressed before comparison), and the expected-file
/// basename under `expected/<cell>/`.
struct Output {
    produced: &'static str,
    gz: bool,
    expected: &'static str,
}

fn fixtures_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

fn read_maybe_gz(path: &Path, gz: bool) -> Vec<u8> {
    let bytes = fs::read(path).unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));
    if gz {
        let mut d = GzDecoder::new(&bytes[..]);
        let mut out = Vec::new();
        d.read_to_end(&mut out)
            .unwrap_or_else(|e| panic!("gunzip {}: {e}", path.display()));
        out
    } else {
        bytes
    }
}

/// Run one cell: copy fixtures into a temp dir, invoke the binary with the
/// cell's flags, then compare each decompressed output to the committed
/// Perl-generated expected file.
fn run_cell(cell: &str, flags: &[&str], outputs: &[Output]) {
    let fx = fixtures_dir();
    let tmp = TempDir::new().unwrap();
    for f in FIXTURE_FILES {
        fs::copy(fx.join(f), tmp.path().join(f)).unwrap();
    }

    let mut cmd = Command::cargo_bin("bismark2bedGraph_rs").unwrap();
    cmd.current_dir(tmp.path());
    cmd.args(flags);
    cmd.args(["-o", "out.bedGraph"]);
    cmd.args(FIXTURE_FILES);
    cmd.assert().success();

    for o in outputs {
        let got = read_maybe_gz(&tmp.path().join(o.produced), o.gz);
        let expected_path = fx.join("expected").join(cell).join(o.expected);
        let expected = fs::read(&expected_path)
            .unwrap_or_else(|e| panic!("reading expected {}: {e}", expected_path.display()));
        assert_eq!(
            got, expected,
            "cell `{cell}` output `{}` differs from Perl-generated expected `{}`",
            o.produced, o.expected
        );
    }
}

const BEDGRAPH: Output = Output {
    produced: "out.bedGraph.gz",
    gz: true,
    expected: "bedGraph",
};
const COV: Output = Output {
    produced: "out.bismark.cov.gz",
    gz: true,
    expected: "cov",
};
const ZERO: Output = Output {
    produced: "out.bedGraph.gz.bismark.zero.cov",
    gz: false,
    expected: "zero",
};
const UCSC: Output = Output {
    produced: "out.bedGraph_UCSC.bedGraph.gz",
    gz: true,
    expected: "ucsc",
};

#[test]
fn cell_default() {
    run_cell("default", &[], &[BEDGRAPH, COV]);
}

#[test]
fn cell_cutoff3() {
    run_cell("cutoff3", &["--cutoff", "3"], &[BEDGRAPH, COV]);
}

#[test]
fn cell_cutoff10() {
    run_cell("cutoff10", &["--cutoff", "10"], &[BEDGRAPH, COV]);
}

#[test]
fn cell_cx() {
    run_cell("cx", &["--CX"], &[BEDGRAPH, COV]);
}

#[test]
fn cell_cx_cutoff2() {
    run_cell("cx_cutoff2", &["--CX", "--cutoff", "2"], &[BEDGRAPH, COV]);
}

#[test]
fn cell_zero() {
    run_cell("zero", &["--zero_based"], &[BEDGRAPH, COV, ZERO]);
}

#[test]
fn cell_ucsc() {
    run_cell("ucsc", &["--ucsc"], &[BEDGRAPH, COV, UCSC]);
}

#[test]
fn cell_zero_ucsc() {
    run_cell(
        "zero_ucsc",
        &["--zero_based", "--ucsc"],
        &[BEDGRAPH, COV, ZERO, UCSC],
    );
}
