//! Phase B byte-identity golden tests + streaming edge cases.
//!
//! Goldens in `tests/data/phase_b/*.golden` are generated by
//! `tests/data/phase_b/generate_goldens.sh` from the repo's Perl
//! `coverage2cytosine` v0.25.1 (self-contained Perl). The Rust binary's output
//! must be raw-byte-identical to each golden across the flag matrix.

use std::path::{Path, PathBuf};

use assert_cmd::Command;

fn data_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/data/phase_b")
}

/// Run the binary for one mode into a tempdir and assert the report + summary
/// are byte-identical to the committed Perl goldens.
fn assert_mode_matches_golden(mode: &str, report_suffix: &str, extra: &[&str]) {
    let d = data_dir();
    let tmp = tempfile::tempdir().unwrap();

    let mut cmd = Command::cargo_bin("coverage2cytosine_rs").unwrap();
    cmd.arg("-o")
        .arg(mode)
        .arg("-g")
        .arg(d.join("genome"))
        .arg("--dir")
        .arg(tmp.path())
        .args(extra)
        .arg(d.join("in.cov"))
        .assert()
        .success();

    // Raw-byte compare (review B-M1): `from_utf8_lossy` could collapse distinct
    // invalid bytes and mask a regression. Compare `Vec<u8>` directly; show the
    // lossy text only in the failure message for debugging.
    let got_report = std::fs::read(tmp.path().join(format!("{mode}.{report_suffix}"))).unwrap();
    let want_report = std::fs::read(d.join(format!("{mode}.report.golden"))).unwrap();
    assert_eq!(
        got_report,
        want_report,
        "{mode}: report bytes differ from Perl golden\n--- got ---\n{}\n--- want ---\n{}",
        String::from_utf8_lossy(&got_report),
        String::from_utf8_lossy(&want_report)
    );

    let got_sum = std::fs::read(
        tmp.path()
            .join(format!("{mode}.cytosine_context_summary.txt")),
    )
    .unwrap();
    let want_sum = std::fs::read(d.join(format!("{mode}.summary.golden"))).unwrap();
    assert_eq!(
        got_sum,
        want_sum,
        "{mode}: context-summary bytes differ from Perl golden\n--- got ---\n{}\n--- want ---\n{}",
        String::from_utf8_lossy(&got_sum),
        String::from_utf8_lossy(&want_sum)
    );
}

#[test]
fn golden_default_cpg() {
    assert_mode_matches_golden("default", "CpG_report.txt", &[]);
}

#[test]
fn golden_cx() {
    assert_mode_matches_golden("cx", "CX_report.txt", &["--CX"]);
}

#[test]
fn golden_zero_based() {
    assert_mode_matches_golden("zero", "CpG_report.txt", &["--zero_based"]);
}

#[test]
fn golden_coverage_threshold() {
    assert_mode_matches_golden("thr", "CpG_report.txt", &["--coverage_threshold", "5"]);
}

// ── Streaming edge cases the sorted-cov goldens can't exercise ──

/// Build a one-chromosome genome dir + a cov file, run the binary, return the
/// CpG report contents.
fn run_with(genome_fa: &str, cov: &str, extra: &[&str]) -> String {
    let tmp = tempfile::tempdir().unwrap();
    let gdir = tmp.path().join("g");
    std::fs::create_dir(&gdir).unwrap();
    std::fs::write(gdir.join("g.fa"), genome_fa).unwrap();
    let cov_path = tmp.path().join("in.cov");
    std::fs::write(&cov_path, cov).unwrap();
    let out = tmp.path().join("out");
    std::fs::create_dir(&out).unwrap();

    let mut cmd = Command::cargo_bin("coverage2cytosine_rs").unwrap();
    cmd.arg("-o")
        .arg("s")
        .arg("-g")
        .arg(&gdir)
        .arg("--dir")
        .arg(&out)
        .args(extra)
        .arg(&cov_path)
        .assert()
        .success();
    std::fs::read_to_string(out.join("s.CpG_report.txt")).unwrap()
}

#[test]
fn non_contiguous_chromosome_re_emits() {
    // chrA … chrB … chrA: Perl flushes on every transition, so chrA's report
    // is emitted TWICE (the 2nd time with only the 2nd block's coverage).
    // Genome chrA "ACGT" has one CpG (C@pos2 +, G@pos3 -).
    let genome = ">chrA\nACGT\n>chrB\nACGT\n";
    let cov = "chrA\t2\t2\t100\t9\t0\nchrB\t2\t2\t100\t1\t0\nchrA\t3\t3\t100\t7\t0\n";
    let report = run_with(genome, cov, &[]);
    // chrA appears twice; first block covers pos2 (9,0), second covers pos3 (7,0).
    let chra_lines: Vec<&str> = report.lines().filter(|l| l.starts_with("chrA\t")).collect();
    assert!(
        chra_lines.len() >= 4,
        "chrA should be re-emitted (2 CpG lines × 2 flushes); got {chra_lines:?}"
    );
    assert!(report.contains("chrA\t2\t+\t9\t0\tCG")); // 1st flush has pos2 coverage
    assert!(report.contains("chrA\t3\t-\t7\t0\tCG")); // 2nd flush has pos3 coverage
}

#[test]
fn empty_coverage_input_standard_path_emits_all_zero_report() {
    // REWRITTEN (was `empty_coverage_input_errors`): plan
    // 06142026_empty-sample-extractor-c2c makes a cleanly-read but EMPTY
    // coverage file on the STANDARD path (threshold 0, no --nome-seq/--gc) a
    // graceful all-zero genome-wide report (exit 0) instead of erroring — so a
    // no-alignment methylseq sample survives. DELIBERATE divergence from Perl.
    let tmp = tempfile::tempdir().unwrap();
    let gdir = tmp.path().join("g");
    std::fs::create_dir(&gdir).unwrap();
    // chrA "ACGT": one CpG dinucleotide → C@pos2 (+) and G@pos3 (-) = 2 Cs.
    std::fs::write(gdir.join("g.fa"), ">chrA\nACGT\n").unwrap();
    let cov = tmp.path().join("empty.cov");
    std::fs::write(&cov, "").unwrap();

    Command::cargo_bin("coverage2cytosine_rs")
        .unwrap()
        .arg("-o")
        .arg("s")
        .arg("-g")
        .arg(&gdir)
        .arg("--dir")
        .arg(tmp.path())
        .arg(&cov)
        .assert()
        .success();

    // All-zero report: every genome cytosine emitted with 0/0 counts.
    let report = std::fs::read_to_string(tmp.path().join("s.CpG_report.txt")).unwrap();
    let rows: Vec<&str> = report.lines().filter(|l| !l.is_empty()).collect();
    assert_eq!(
        rows.len(),
        2,
        "row count must equal the genome CpG cytosine count (2); got {rows:?}"
    );
    assert!(report.contains("chrA\t2\t+\t0\t0\tCG"));
    assert!(report.contains("chrA\t3\t-\t0\t0\tCG"));
    // The context summary must also exist.
    assert!(
        tmp.path().join("s.cytosine_context_summary.txt").exists(),
        "cytosine_context_summary.txt must exist on the graceful-empty path"
    );
}

#[test]
fn empty_coverage_gzipped_standard_path_emits_gzipped_all_zero_report() {
    // Task #4: an empty (validly-gzipped) `.cov.gz` + `--gzip` on the standard
    // path → exit 0; `*report.txt.gz` (GZIPPED, all-zero rows) + summary exist;
    // row count == genome cytosine count. Mirrors methylseq's c2c shape.
    use std::io::Write;

    let tmp = tempfile::tempdir().unwrap();
    let gdir = tmp.path().join("g");
    std::fs::create_dir(&gdir).unwrap();
    std::fs::write(gdir.join("g.fa"), ">chrA\nACGT\n").unwrap();
    // A VALID empty gzip stream (0 data bytes) named `.cov.gz`.
    let cov = tmp.path().join("empty.cov.gz");
    let f = std::fs::File::create(&cov).unwrap();
    let mut enc = flate2::write::GzEncoder::new(f, flate2::Compression::default());
    enc.write_all(b"").unwrap();
    enc.finish().unwrap();

    Command::cargo_bin("coverage2cytosine_rs")
        .unwrap()
        .arg("-o")
        .arg("s")
        .arg("-g")
        .arg(&gdir)
        .arg("--dir")
        .arg(tmp.path())
        .arg("--gzip")
        .arg(&cov)
        .assert()
        .success();

    let report_gz = tmp.path().join("s.CpG_report.txt.gz");
    assert!(
        report_gz.exists(),
        "gzipped report *report.txt.gz must exist"
    );
    // Decompress + assert all-zero rows == genome cytosine count (2).
    let bytes = std::fs::read(&report_gz).unwrap();
    let mut d = flate2::read::MultiGzDecoder::new(&bytes[..]);
    let mut report = String::new();
    std::io::Read::read_to_string(&mut d, &mut report).unwrap();
    let rows: Vec<&str> = report.lines().filter(|l| !l.is_empty()).collect();
    assert_eq!(
        rows.len(),
        2,
        "row count must equal genome C count; got {rows:?}"
    );
    assert!(report.contains("chrA\t2\t+\t0\t0\tCG"));
    assert!(report.contains("chrA\t3\t-\t0\t0\tCG"));
    assert!(
        tmp.path().join("s.cytosine_context_summary.txt").exists(),
        "context summary must exist"
    );
}

#[test]
fn empty_coverage_missing_file_errors() {
    // A genuine read failure (the cov file does not exist) must STILL error —
    // graceful-empty is ONLY for a cleanly-read but empty file.
    let tmp = tempfile::tempdir().unwrap();
    let gdir = tmp.path().join("g");
    std::fs::create_dir(&gdir).unwrap();
    std::fs::write(gdir.join("g.fa"), ">chrA\nACGT\n").unwrap();
    let missing = tmp.path().join("does_not_exist.cov");

    Command::cargo_bin("coverage2cytosine_rs")
        .unwrap()
        .arg("-o")
        .arg("s")
        .arg("-g")
        .arg(&gdir)
        .arg("--dir")
        .arg(tmp.path())
        .arg(&missing)
        .assert()
        .failure();
}

#[test]
fn empty_coverage_corrupt_gzip_with_gz_name_errors() {
    // A `.gz`-named file with non-gzip (corrupt) content must STILL error: the
    // read fails (propagated via `?`) BEFORE the empty-but-valid `None` arm, so
    // graceful-empty never engages. Guards against the relax masking a genuine
    // decompression failure.
    let tmp = tempfile::tempdir().unwrap();
    let gdir = tmp.path().join("g");
    std::fs::create_dir(&gdir).unwrap();
    std::fs::write(gdir.join("g.fa"), ">chrA\nACGT\n").unwrap();
    let cov = tmp.path().join("corrupt.cov.gz");
    // Not a valid gzip stream — open_cov sees the `.gz` name and tries to
    // decompress, which fails.
    std::fs::write(&cov, b"this is not gzip data at all\n").unwrap();

    Command::cargo_bin("coverage2cytosine_rs")
        .unwrap()
        .arg("-o")
        .arg("s")
        .arg("-g")
        .arg(&gdir)
        .arg("--dir")
        .arg(tmp.path())
        .arg(&cov)
        .assert()
        .failure();
}

/// Assert a graceful empty c2c run produced a report file + a cytosine-context
/// summary (methylseq's required outputs) in `dir`.
fn assert_report_and_summary_present(dir: &std::path::Path) {
    let names: Vec<String> = std::fs::read_dir(dir)
        .unwrap()
        .filter_map(|e| e.ok().map(|e| e.file_name().to_string_lossy().into_owned()))
        .collect();
    assert!(
        names.iter().any(|n| n.contains("report")),
        "expected a c2c report file in {names:?}"
    );
    assert!(
        names.iter().any(|n| n.contains("cytosine_context_summary")),
        "expected a cytosine_context_summary file in {names:?}"
    );
}

#[test]
fn empty_coverage_threshold_emits_empty_report() {
    // NOMe follow-up (plan 06142026): graceful-empty now covers EVERY mode
    // except `--gc`. With `--coverage_threshold` the uncovered pass is skipped,
    // so an empty cov yields a correct EMPTY report (no position meets the
    // threshold) + summary at exit 0 — instead of erroring.
    let tmp = tempfile::tempdir().unwrap();
    let gdir = tmp.path().join("g");
    std::fs::create_dir(&gdir).unwrap();
    std::fs::write(gdir.join("g.fa"), ">chrA\nACGT\n").unwrap();
    let cov = tmp.path().join("empty.cov");
    std::fs::write(&cov, "").unwrap();

    Command::cargo_bin("coverage2cytosine_rs")
        .unwrap()
        .arg("-o")
        .arg("s")
        .arg("-g")
        .arg(&gdir)
        .arg("--dir")
        .arg(tmp.path())
        .args(["--coverage_threshold", "1"])
        .arg(&cov)
        .assert()
        .success();
    assert_report_and_summary_present(tmp.path());
}

#[test]
fn empty_coverage_nome_emits_empty_report() {
    // NOMe follow-up (plan 06142026): `--nome-seq` on an empty cov is now
    // GRACEFUL. NOMe reports covered positions only (the uncovered pass is
    // skipped), so zero coverage → a correct EMPTY report + summary at exit 0.
    // This is methylseq's NOMe-seq c2c step (the `--nome-seq` wall) — the fix
    // that unblocks a no-alignment GpC/NOMe sample. Deliberate divergence from
    // Perl (which dies "No last chromosome was defined").
    let tmp = tempfile::tempdir().unwrap();
    let gdir = tmp.path().join("g");
    std::fs::create_dir(&gdir).unwrap();
    std::fs::write(gdir.join("g.fa"), ">chrA\nACGT\n").unwrap();
    let cov = tmp.path().join("empty.cov");
    std::fs::write(&cov, "").unwrap();

    Command::cargo_bin("coverage2cytosine_rs")
        .unwrap()
        .arg("-o")
        .arg("s")
        .arg("-g")
        .arg(&gdir)
        .arg("--dir")
        .arg(tmp.path())
        .arg("--nome-seq")
        .arg(&cov)
        .assert()
        .success();
    assert_report_and_summary_present(tmp.path());
}

#[test]
fn empty_coverage_gc_emits_empty_report() {
    // NOMe follow-up (plan 06142026): `--gc` on an empty cov is now GRACEFUL.
    // run_report produces the all-zero core report + summary (uncovered pass runs:
    // threshold 0, non-NOMe), and the GpC pass (gpc.rs) is itself empty-graceful
    // (no guard — its loop no-ops + finishes empty writers). exit 0. The stale
    // "gpc relies on the guard" doc was over-cautious; gpc handles empty fine.
    let tmp = tempfile::tempdir().unwrap();
    let gdir = tmp.path().join("g");
    std::fs::create_dir(&gdir).unwrap();
    std::fs::write(gdir.join("g.fa"), ">chrA\nACGT\n").unwrap();
    let cov = tmp.path().join("empty.cov");
    std::fs::write(&cov, "").unwrap();

    Command::cargo_bin("coverage2cytosine_rs")
        .unwrap()
        .arg("-o")
        .arg("s")
        .arg("-g")
        .arg(&gdir)
        .arg("--dir")
        .arg(tmp.path())
        .arg("--gc")
        .arg(&cov)
        .assert()
        .success();
    assert_report_and_summary_present(tmp.path());
}

#[test]
fn cov_chromosome_absent_from_genome_emits_nothing_for_it() {
    // cov references chrZ (not in genome) — it must not panic or emit chrZ.
    let genome = ">chrA\nACGT\n";
    let cov = "chrZ\t2\t2\t100\t5\t0\n";
    let report = run_with(genome, cov, &[]);
    assert!(!report.contains("chrZ"));
    // chrA is uncovered → emitted in the uncovered pass with 0,0.
    assert!(report.contains("chrA\t2\t+\t0\t0\tCG"));
}

#[test]
fn covered_chromosomes_emit_in_cov_appearance_order_not_sorted() {
    // V10 (review B-M2): genome FASTA order is chrA,chrB and sorted order is
    // chrA,chrB — but the cov lists chrB BEFORE chrA. Covered output must
    // follow COV appearance order (chrB then chrA), discriminating against a
    // genome-order or sorted-order implementation.
    let genome = ">chrA\nACGT\n>chrB\nACGT\n";
    let cov = "chrB\t2\t2\t100\t5\t0\nchrA\t2\t2\t100\t7\t0\n";
    let report = run_with(genome, cov, &[]);
    let b_pos = report.find("chrB\t").unwrap();
    let a_pos = report.find("chrA\t").unwrap();
    assert!(
        b_pos < a_pos,
        "covered chrB (first in cov) must precede chrA; got:\n{report}"
    );
}

#[test]
fn duplicate_position_last_write_wins() {
    // V21: two cov lines at the same chr+pos — the LAST counts win (Perl %chr
    // hash overwrite; Rust HashMap::insert).
    let genome = ">chrA\nACGT\n";
    let cov = "chrA\t2\t2\t100\t9\t0\nchrA\t2\t2\t100\t3\t1\n";
    let report = run_with(genome, cov, &[]);
    assert!(
        report.contains("chrA\t2\t+\t3\t1\tCG"),
        "last write (3,1) must win; got:\n{report}"
    );
    assert!(
        !report.contains("chrA\t2\t+\t9\t0"),
        "first write (9,0) must be overwritten; got:\n{report}"
    );
}

#[test]
fn three_way_covered_then_uncovered_sorted() {
    // V23: genome chrA,chrM,chrZ; cov covers only chrM. Output: covered chrM
    // first (cov pass), then uncovered chrA,chrZ in bytewise-sorted order —
    // proving the covered-appearance and uncovered-sorted passes are distinct.
    let genome = ">chrA\nACGT\n>chrM\nACGT\n>chrZ\nACGT\n";
    let cov = "chrM\t2\t2\t100\t5\t0\n";
    let report = run_with(genome, cov, &[]);
    let m = report.find("chrM\t").unwrap();
    let a = report.find("chrA\t").unwrap();
    let z = report.find("chrZ\t").unwrap();
    assert!(
        m < a && a < z,
        "expected covered chrM, then uncovered chrA<chrZ; got:\n{report}"
    );
}

#[test]
fn blank_and_trailing_lines_are_ignored_end_to_end() {
    // V22: a blank line + trailing newline in the cov must not create a phantom
    // chromosome or trip the empty-input guard.
    let genome = ">chrA\nACGT\n";
    let cov = "chrA\t2\t2\t100\t5\t0\n\nchrA\t3\t3\t100\t4\t0\n";
    let report = run_with(genome, cov, &[]);
    assert!(report.contains("chrA\t2\t+\t5\t0\tCG"));
    assert!(report.contains("chrA\t3\t-\t4\t0\tCG"));
}
