//! Phase 1 byte-identity golden tests: `--gc`/`--gc_context` (GpC report + cov)
//! and `--nome-seq` (NOMe-filtered core report + cov + GpC report + cov).
//!
//! Goldens in `tests/data/phase1/gold/<mode>/` are the Perl v0.25.1 output for
//! each mode (regenerated by `tests/data/phase1/generate_goldens.sh`). Each test
//! runs the Rust binary into a tempdir and compares the **file set** and every
//! file's bytes against the matching golden directory. gzip modes decompress
//! the Rust output and compare to the corresponding plain golden (gzip is
//! content-invariant — the same discipline as `golden_phase_d`).
//!
//! Covers PLAN §9 V4–V21 + the raw-`-o` NOMe `.cov` base divergence (the NOMe
//! `.cov` derives from the un-stripped `-o`, unlike the report — see
//! `report::nome_cov_path`).

use std::io::Read;
use std::path::{Path, PathBuf};

use assert_cmd::Command;
use flate2::read::MultiGzDecoder;

fn d1() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/data/phase1")
}
fn gold(mode: &str) -> PathBuf {
    d1().join("gold").join(mode)
}

fn gunzip(path: &Path) -> Vec<u8> {
    let mut d = MultiGzDecoder::new(std::fs::File::open(path).unwrap());
    let mut out = Vec::new();
    d.read_to_end(&mut out).unwrap();
    out
}

fn list_sorted(dir: &Path) -> Vec<String> {
    let mut v: Vec<String> = std::fs::read_dir(dir)
        .unwrap()
        .map(|e| e.unwrap().file_name().into_string().unwrap())
        .collect();
    v.sort();
    v
}

/// Run `coverage2cytosine_rs` into a fresh tempdir; assert success; return it.
fn run_rust(genome: &str, cov: &str, oname: &str, flags: &[&str]) -> tempfile::TempDir {
    let tmp = tempfile::tempdir().unwrap();
    Command::cargo_bin("coverage2cytosine")
        .unwrap()
        .arg("-o")
        .arg(oname)
        .arg("-g")
        .arg(d1().join(genome))
        .arg("--dir")
        .arg(tmp.path())
        .args(flags)
        .arg(d1().join(cov))
        .assert()
        .success();
    tmp
}

/// Assert the Rust output dir matches the golden dir: identical file set and
/// byte-identical contents (plain files).
fn assert_dir_matches(rust_dir: &Path, mode: &str) {
    let g = gold(mode);
    assert_eq!(
        list_sorted(rust_dir),
        list_sorted(&g),
        "[{mode}] file-set mismatch"
    );
    for f in list_sorted(&g) {
        assert_eq!(
            std::fs::read(rust_dir.join(&f)).unwrap(),
            std::fs::read(g.join(&f)).unwrap(),
            "[{mode}] bytes differ in {f}"
        );
    }
}

/// Assert a `--gzip` Rust output dir matches a PLAIN golden dir: the summary
/// stays plain, every other file gains `.gz` and decompresses byte-identically.
fn assert_gz_matches_plain(rust_dir: &Path, plain_mode: &str) {
    let g = gold(plain_mode);
    let gold_files = list_sorted(&g);
    let mut expected: Vec<String> = gold_files
        .iter()
        .map(|f| {
            if f.ends_with(".cytosine_context_summary.txt") {
                f.clone()
            } else {
                format!("{f}.gz")
            }
        })
        .collect();
    expected.sort();
    assert_eq!(
        list_sorted(rust_dir),
        expected,
        "[{plain_mode}+gzip] file-set mismatch"
    );
    for f in &gold_files {
        let want = std::fs::read(g.join(f)).unwrap();
        let got = if f.ends_with(".cytosine_context_summary.txt") {
            std::fs::read(rust_dir.join(f)).unwrap()
        } else {
            gunzip(&rust_dir.join(format!("{f}.gz")))
        };
        assert_eq!(
            got, want,
            "[{plain_mode}+gzip] decompressed bytes differ in {f}"
        );
    }
}

// ── --gc / --gc_context (GpC report + cov, core report still emitted) ──

#[test]
fn v4_gc_primary_matches_perl() {
    // GpC report + cov (bottom-before-top, CG-context GpCs present) AND the core
    // CpG report, all byte-identical to Perl.
    let tmp = run_rust("g_primary", "primary.cov", "sample", &["--gc"]);
    assert_dir_matches(tmp.path(), "gc_primary");
}

#[test]
fn v5_gc_core_report_unaffected() {
    // `--gc` only ADDS the GpC stream — the core CpG report (threshold 0, incl.
    // the uncovered all-zero CpGs) is unchanged. Proven on the RUST output: the
    // `--gc` run's core report must equal a plain RUST run AND the plain Perl
    // golden (not merely two Perl goldens to each other).
    let gc = run_rust("g_primary", "primary.cov", "sample", &["--gc"]);
    let plain = run_rust("g_primary", "primary.cov", "sample", &[]);
    let gc_core = std::fs::read(gc.path().join("sample.CpG_report.txt")).unwrap();
    let plain_core = std::fs::read(plain.path().join("sample.CpG_report.txt")).unwrap();
    assert_eq!(
        gc_core, plain_core,
        "--gc must not perturb the core CpG report"
    );
    assert_eq!(
        gc_core,
        std::fs::read(gold("plain_primary").join("sample.CpG_report.txt")).unwrap(),
        "the --gc core report must match the plain Perl golden",
    );
}

#[test]
fn v8_gc_gzip_decompresses_to_plain_golden() {
    let tmp = run_rust("g_primary", "primary.cov", "sample", &["--gc", "--gzip"]);
    assert_gz_matches_plain(tmp.path(), "gc_primary");
}

#[test]
fn v6_gc_edge_guards_match_perl() {
    // First/last GC dropped; only the interior GC emits.
    let tmp = run_rust("g_edge", "edge.cov", "sample", &["--gc"]);
    assert_dir_matches(tmp.path(), "gc_edge");
}

#[test]
fn v7_gc_gcgc_non_overlapping_matches_perl() {
    let tmp = run_rust("g_gcgc", "gcgc.cov", "sample", &["--gc"]);
    assert_dir_matches(tmp.path(), "gc_gcgc");
}

#[test]
fn v10_v20_gc_zero_based_core_shifts_gpc_frozen() {
    // Whole-dir match for `--gc --zero_based`.
    let tmp = run_rust(
        "g_primary",
        "primary.cov",
        "sample",
        &["--gc", "--zero_based"],
    );
    assert_dir_matches(tmp.path(), "gc_zero");
    // V10: the GpC report/cov are FROZEN 1-based (no `--zero_based` branch).
    assert_eq!(
        std::fs::read(gold("gc_zero").join("sample.GpC_report.txt")).unwrap(),
        std::fs::read(gold("gc_primary").join("sample.GpC_report.txt")).unwrap(),
        "GpC report must be identical with/without --zero_based",
    );
    assert_eq!(
        std::fs::read(gold("gc_zero").join("sample.GpC.cov")).unwrap(),
        std::fs::read(gold("gc_primary").join("sample.GpC.cov")).unwrap(),
    );
    // V20: the CORE report DOES shift under --zero_based (asymmetry discriminator).
    assert_ne!(
        std::fs::read(gold("gc_zero").join("sample.CpG_report.txt")).unwrap(),
        std::fs::read(gold("gc_primary").join("sample.CpG_report.txt")).unwrap(),
        "core report must shift under --zero_based",
    );
}

#[test]
fn b_m2_gc_threshold_runs_core_at_user_threshold() {
    // `--gc --coverage_threshold 3`: core report at 3 (no uncovered pass), GpC
    // walk at max(3,1)=3.
    let tmp = run_rust(
        "g_primary",
        "primary.cov",
        "sample",
        &["--gc", "--coverage_threshold", "3"],
    );
    assert_dir_matches(tmp.path(), "gc_thr3");
}

#[test]
fn v15_gc_raw_suffix_filename_matches_perl() {
    // `-o sample.CpG_report.txt --gc` → GpC files use the RAW (un-stripped) -o.
    let tmp = run_rust(
        "g_primary",
        "primary.cov",
        "sample.CpG_report.txt",
        &["--gc"],
    );
    assert_dir_matches(tmp.path(), "gc_rawsuffix");
}

#[test]
fn v9_gc_split_multi_chromosome_matches_perl() {
    let tmp = run_rust(
        "g_multi",
        "multi.cov",
        "sample",
        &["--gc", "--split_by_chromosome"],
    );
    assert_dir_matches(tmp.path(), "gc_split");
}

#[test]
fn v18_gc_non_contiguous_chr_reappearance_single() {
    // cov order chr1, chr2, chr1 → single-file re-emits the chr1 GpC block.
    let tmp = run_rust("g_multi", "noncontig.cov", "sample", &["--gc"]);
    assert_dir_matches(tmp.path(), "gc_noncontig");
}

#[test]
fn v18_gc_non_contiguous_chr_reappearance_split() {
    // split mode → the per-chr chr1 files are re-truncated to the LAST segment.
    let tmp = run_rust(
        "g_multi",
        "noncontig.cov",
        "sample",
        &["--gc", "--split_by_chromosome"],
    );
    assert_dir_matches(tmp.path(), "gc_noncontig_spl");
}

// ── --nome-seq (NOMe core + GpC filtering) ──

#[test]
fn v12_nome_primary_matches_perl() {
    // No covered ACG/TCG CpG → empty NOMe core report; NOMe GpC keeps only the
    // CHH GpC (CG-context GpCs dropped). Summary has NO `.NOMe` infix (V13).
    let tmp = run_rust("g_primary", "primary.cov", "sample", &["--nome-seq"]);
    assert_dir_matches(tmp.path(), "nome_primary");
}

#[test]
fn v11_nome_acg_tcg_upstream_filter_matches_perl() {
    // NOMe core report keeps only ACG/TCG-upstream CpGs (+ the `.NOMe.CpG.cov`
    // companion); `-` strand uses the revcomp'd upstream.
    let tmp = run_rust("g_nome", "nome.cov", "sample", &["--nome-seq"]);
    assert_dir_matches(tmp.path(), "nome_acgtcg");
}

#[test]
fn v21_nome_zero_based_point_cov_coord() {
    // `--nome-seq --zero_based`: core report + `.NOMe.CpG.cov` shift to pos-1
    // (the cov is a POINT coord pos-1,pos-1); GpC cov stays frozen 1-based.
    let tmp = run_rust(
        "g_nome",
        "nome.cov",
        "sample",
        &["--nome-seq", "--zero_based"],
    );
    assert_dir_matches(tmp.path(), "nome_zero");
}

#[test]
fn nome_gzip_decompresses_to_plain_golden() {
    let tmp = run_rust("g_nome", "nome.cov", "sample", &["--nome-seq", "--gzip"]);
    assert_gz_matches_plain(tmp.path(), "nome_acgtcg");
}

#[test]
fn v14_v19_nome_split_matches_perl() {
    // `--nome-seq --split_by_chromosome`: per-chr `.NOMe.{CpG,GpC}_report/.cov`
    // (the only path through Perl's `$nome`-true `close GCCOV` branch); covered
    // chromosomes only (V14: cov has chr1+chr2, no uncovered all-zero pass).
    let tmp = run_rust(
        "g_multi",
        "multi.cov",
        "sample",
        &["--nome-seq", "--split_by_chromosome"],
    );
    assert_dir_matches(tmp.path(), "nome_split");
}

#[test]
fn nome_raw_suffix_cov_uses_raw_base() {
    // `-o sample.CpG_report.txt --nome-seq`: the core REPORT drops the suffix
    // (`sample.NOMe.CpG_report.txt`) while the core/GpC `.cov` keep the RAW base
    // (`sample.CpG_report.txt.NOMe.*`) — the file-set divergence verified against
    // live Perl (NOT the plan's `{stem}.NOMe.CpG.cov` prose).
    let tmp = run_rust(
        "g_nome",
        "nome.cov",
        "sample.CpG_report.txt",
        &["--nome-seq"],
    );
    assert_dir_matches(tmp.path(), "nome_rawsuffix");
}

// ── Regression: plain runs are unchanged (V17) ──

#[test]
fn v17_plain_run_writes_no_cov_or_gpc_or_nome_files() {
    // A plain run (no --gc/--nome-seq) emits ONLY the core report + summary —
    // no `.cov`, `.GpC.*`, or `.NOMe.*` files (the golden dir has exactly two).
    let tmp = run_rust("g_primary", "primary.cov", "sample", &[]);
    assert_dir_matches(tmp.path(), "plain_primary");
}
