//! Phase B byte-identity golden tests + streaming edge cases.
//!
//! Goldens in `tests/data/phase_b/*.golden` are generated by
//! `tests/data/phase_b/generate_goldens.sh` from the repo's Perl
//! `coverage2cytosine` v0.25.1 (self-contained Perl). The Rust binary's output
//! must be raw-byte-identical to each golden across the flag matrix.

use std::path::{Path, PathBuf};

use assert_cmd::Command;

fn data_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/data/phase_b")
}

/// Run the binary for one mode into a tempdir and assert the report + summary
/// are byte-identical to the committed Perl goldens.
fn assert_mode_matches_golden(mode: &str, report_suffix: &str, extra: &[&str]) {
    let d = data_dir();
    let tmp = tempfile::tempdir().unwrap();

    let mut cmd = Command::cargo_bin("coverage2cytosine_rs").unwrap();
    cmd.arg("-o")
        .arg(mode)
        .arg("-g")
        .arg(d.join("genome"))
        .arg("--dir")
        .arg(tmp.path())
        .args(extra)
        .arg(d.join("in.cov"))
        .assert()
        .success();

    // Raw-byte compare (review B-M1): `from_utf8_lossy` could collapse distinct
    // invalid bytes and mask a regression. Compare `Vec<u8>` directly; show the
    // lossy text only in the failure message for debugging.
    let got_report = std::fs::read(tmp.path().join(format!("{mode}.{report_suffix}"))).unwrap();
    let want_report = std::fs::read(d.join(format!("{mode}.report.golden"))).unwrap();
    assert_eq!(
        got_report,
        want_report,
        "{mode}: report bytes differ from Perl golden\n--- got ---\n{}\n--- want ---\n{}",
        String::from_utf8_lossy(&got_report),
        String::from_utf8_lossy(&want_report)
    );

    let got_sum = std::fs::read(
        tmp.path()
            .join(format!("{mode}.cytosine_context_summary.txt")),
    )
    .unwrap();
    let want_sum = std::fs::read(d.join(format!("{mode}.summary.golden"))).unwrap();
    assert_eq!(
        got_sum,
        want_sum,
        "{mode}: context-summary bytes differ from Perl golden\n--- got ---\n{}\n--- want ---\n{}",
        String::from_utf8_lossy(&got_sum),
        String::from_utf8_lossy(&want_sum)
    );
}

#[test]
fn golden_default_cpg() {
    assert_mode_matches_golden("default", "CpG_report.txt", &[]);
}

#[test]
fn golden_cx() {
    assert_mode_matches_golden("cx", "CX_report.txt", &["--CX"]);
}

#[test]
fn golden_zero_based() {
    assert_mode_matches_golden("zero", "CpG_report.txt", &["--zero_based"]);
}

#[test]
fn golden_coverage_threshold() {
    assert_mode_matches_golden("thr", "CpG_report.txt", &["--coverage_threshold", "5"]);
}

// ── Streaming edge cases the sorted-cov goldens can't exercise ──

/// Build a one-chromosome genome dir + a cov file, run the binary, return the
/// CpG report contents.
fn run_with(genome_fa: &str, cov: &str, extra: &[&str]) -> String {
    let tmp = tempfile::tempdir().unwrap();
    let gdir = tmp.path().join("g");
    std::fs::create_dir(&gdir).unwrap();
    std::fs::write(gdir.join("g.fa"), genome_fa).unwrap();
    let cov_path = tmp.path().join("in.cov");
    std::fs::write(&cov_path, cov).unwrap();
    let out = tmp.path().join("out");
    std::fs::create_dir(&out).unwrap();

    let mut cmd = Command::cargo_bin("coverage2cytosine_rs").unwrap();
    cmd.arg("-o")
        .arg("s")
        .arg("-g")
        .arg(&gdir)
        .arg("--dir")
        .arg(&out)
        .args(extra)
        .arg(&cov_path)
        .assert()
        .success();
    std::fs::read_to_string(out.join("s.CpG_report.txt")).unwrap()
}

#[test]
fn non_contiguous_chromosome_re_emits() {
    // chrA … chrB … chrA: Perl flushes on every transition, so chrA's report
    // is emitted TWICE (the 2nd time with only the 2nd block's coverage).
    // Genome chrA "ACGT" has one CpG (C@pos2 +, G@pos3 -).
    let genome = ">chrA\nACGT\n>chrB\nACGT\n";
    let cov = "chrA\t2\t2\t100\t9\t0\nchrB\t2\t2\t100\t1\t0\nchrA\t3\t3\t100\t7\t0\n";
    let report = run_with(genome, cov, &[]);
    // chrA appears twice; first block covers pos2 (9,0), second covers pos3 (7,0).
    let chra_lines: Vec<&str> = report.lines().filter(|l| l.starts_with("chrA\t")).collect();
    assert!(
        chra_lines.len() >= 4,
        "chrA should be re-emitted (2 CpG lines × 2 flushes); got {chra_lines:?}"
    );
    assert!(report.contains("chrA\t2\t+\t9\t0\tCG")); // 1st flush has pos2 coverage
    assert!(report.contains("chrA\t3\t-\t7\t0\tCG")); // 2nd flush has pos3 coverage
}

#[test]
fn empty_coverage_input_errors() {
    let tmp = tempfile::tempdir().unwrap();
    let gdir = tmp.path().join("g");
    std::fs::create_dir(&gdir).unwrap();
    std::fs::write(gdir.join("g.fa"), ">chrA\nACGT\n").unwrap();
    let cov = tmp.path().join("empty.cov");
    std::fs::write(&cov, "").unwrap();

    Command::cargo_bin("coverage2cytosine_rs")
        .unwrap()
        .arg("-o")
        .arg("s")
        .arg("-g")
        .arg(&gdir)
        .arg("--dir")
        .arg(tmp.path())
        .arg(&cov)
        .assert()
        .failure()
        .code(1)
        .stderr(predicates::str::contains("no data found"));
}

#[test]
fn cov_chromosome_absent_from_genome_emits_nothing_for_it() {
    // cov references chrZ (not in genome) — it must not panic or emit chrZ.
    let genome = ">chrA\nACGT\n";
    let cov = "chrZ\t2\t2\t100\t5\t0\n";
    let report = run_with(genome, cov, &[]);
    assert!(!report.contains("chrZ"));
    // chrA is uncovered → emitted in the uncovered pass with 0,0.
    assert!(report.contains("chrA\t2\t+\t0\t0\tCG"));
}

#[test]
fn covered_chromosomes_emit_in_cov_appearance_order_not_sorted() {
    // V10 (review B-M2): genome FASTA order is chrA,chrB and sorted order is
    // chrA,chrB — but the cov lists chrB BEFORE chrA. Covered output must
    // follow COV appearance order (chrB then chrA), discriminating against a
    // genome-order or sorted-order implementation.
    let genome = ">chrA\nACGT\n>chrB\nACGT\n";
    let cov = "chrB\t2\t2\t100\t5\t0\nchrA\t2\t2\t100\t7\t0\n";
    let report = run_with(genome, cov, &[]);
    let b_pos = report.find("chrB\t").unwrap();
    let a_pos = report.find("chrA\t").unwrap();
    assert!(
        b_pos < a_pos,
        "covered chrB (first in cov) must precede chrA; got:\n{report}"
    );
}

#[test]
fn duplicate_position_last_write_wins() {
    // V21: two cov lines at the same chr+pos — the LAST counts win (Perl %chr
    // hash overwrite; Rust HashMap::insert).
    let genome = ">chrA\nACGT\n";
    let cov = "chrA\t2\t2\t100\t9\t0\nchrA\t2\t2\t100\t3\t1\n";
    let report = run_with(genome, cov, &[]);
    assert!(
        report.contains("chrA\t2\t+\t3\t1\tCG"),
        "last write (3,1) must win; got:\n{report}"
    );
    assert!(
        !report.contains("chrA\t2\t+\t9\t0"),
        "first write (9,0) must be overwritten; got:\n{report}"
    );
}

#[test]
fn three_way_covered_then_uncovered_sorted() {
    // V23: genome chrA,chrM,chrZ; cov covers only chrM. Output: covered chrM
    // first (cov pass), then uncovered chrA,chrZ in bytewise-sorted order —
    // proving the covered-appearance and uncovered-sorted passes are distinct.
    let genome = ">chrA\nACGT\n>chrM\nACGT\n>chrZ\nACGT\n";
    let cov = "chrM\t2\t2\t100\t5\t0\n";
    let report = run_with(genome, cov, &[]);
    let m = report.find("chrM\t").unwrap();
    let a = report.find("chrA\t").unwrap();
    let z = report.find("chrZ\t").unwrap();
    assert!(
        m < a && a < z,
        "expected covered chrM, then uncovered chrA<chrZ; got:\n{report}"
    );
}

#[test]
fn blank_and_trailing_lines_are_ignored_end_to_end() {
    // V22: a blank line + trailing newline in the cov must not create a phantom
    // chromosome or trip the empty-input guard.
    let genome = ">chrA\nACGT\n";
    let cov = "chrA\t2\t2\t100\t5\t0\n\nchrA\t3\t3\t100\t4\t0\n";
    let report = run_with(genome, cov, &[]);
    assert!(report.contains("chrA\t2\t+\t5\t0\tCG"));
    assert!(report.contains("chrA\t3\t-\t4\t0\tCG"));
}
