//! Phase C byte-identity golden tests: `--gzip`, `--split_by_chromosome`, and
//! the two combined. Goldens (`tests/data/phase_b/phase_c/{split,split_thr}/`)
//! are generated by `tests/data/phase_b/generate_goldens.sh` from the repo's
//! Perl `coverage2cytosine` v0.25.1. gzip output is compared **after
//! decompression** (the gzip container is impl-dependent; the content is not).

use std::collections::BTreeSet;
use std::io::Read;
use std::path::{Path, PathBuf};

use assert_cmd::Command;
use flate2::read::MultiGzDecoder;

fn data_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/data/phase_b")
}

fn gunzip(path: &Path) -> Vec<u8> {
    let mut d = MultiGzDecoder::new(std::fs::File::open(path).unwrap());
    let mut out = Vec::new();
    d.read_to_end(&mut out).unwrap();
    out
}

fn file_set(dir: &Path) -> BTreeSet<String> {
    std::fs::read_dir(dir)
        .unwrap()
        .map(|e| e.unwrap().file_name().to_string_lossy().into_owned())
        .collect()
}

/// Run the binary with `flags` (after `-o stem`) into a fresh tempdir; return it.
fn run(stem: &str, flags: &[&str]) -> tempfile::TempDir {
    let d = data_dir();
    let tmp = tempfile::tempdir().unwrap();
    let mut cmd = Command::cargo_bin("coverage2cytosine_rs").unwrap();
    cmd.arg("-o")
        .arg(stem)
        .arg("-g")
        .arg(d.join("genome"))
        .arg("--dir")
        .arg(tmp.path())
        .args(flags)
        .arg(d.join("in.cov"))
        .assert()
        .success();
    tmp
}

// ── --gzip (non-split): decompressed report == plain golden; summary plain ──

#[test]
fn gzip_report_decompresses_to_plain_golden() {
    let d = data_dir();
    let tmp = run("gz", &["--gzip"]);
    let got = gunzip(&tmp.path().join("gz.CpG_report.txt.gz"));
    let want = std::fs::read(d.join("default.report.golden")).unwrap();
    assert_eq!(
        got, want,
        "decompressed --gzip report must equal plain golden"
    );

    // Summary is plain (not gzip) and matches.
    let sum = tmp.path().join("gz.cytosine_context_summary.txt");
    let sum_bytes = std::fs::read(&sum).unwrap();
    assert!(
        !(sum_bytes.len() >= 2 && sum_bytes[0] == 0x1f && sum_bytes[1] == 0x8b),
        "context summary must NOT be gzipped"
    );
    assert_eq!(
        sum_bytes,
        std::fs::read(d.join("default.summary.golden")).unwrap()
    );
}

#[test]
fn gzip_cx_report_decompresses_to_plain_golden() {
    let d = data_dir();
    let tmp = run("cx", &["--CX", "--gzip"]);
    let got = gunzip(&tmp.path().join("cx.CX_report.txt.gz"));
    assert_eq!(got, std::fs::read(d.join("cx.report.golden")).unwrap());

    // Summary stays plain (not gzipped) even with --CX --gzip, and matches.
    let sum_bytes = std::fs::read(tmp.path().join("cx.cytosine_context_summary.txt")).unwrap();
    assert!(
        !(sum_bytes.len() >= 2 && sum_bytes[0] == 0x1f && sum_bytes[1] == 0x8b),
        "context summary must NOT be gzipped"
    );
    assert_eq!(
        sum_bytes,
        std::fs::read(d.join("cx.summary.golden")).unwrap()
    );
}

// ── --split_by_chromosome: whole-dir byte-identity to the Perl golden dir ──

#[test]
fn split_dir_matches_perl_golden() {
    let golden = data_dir().join("phase_c/split");
    let tmp = run("split", &["--split_by_chromosome"]);
    // File SET (bidirectional).
    assert_eq!(
        file_set(tmp.path()),
        file_set(&golden),
        "split file set must equal Perl's exactly"
    );
    // Per-file bytes (incl. the empty-vs-last-full summary quirk).
    for name in file_set(&golden) {
        let got = std::fs::read(tmp.path().join(&name)).unwrap();
        let want = std::fs::read(golden.join(&name)).unwrap();
        assert_eq!(got, want, "split file {name} differs from golden");
    }
}

#[test]
fn split_threshold_dir_matches_perl_golden() {
    // --split --coverage_threshold 5 → only covered chrs get files (no uncovered pass).
    let golden = data_dir().join("phase_c/split_thr");
    let tmp = run(
        "split",
        &["--split_by_chromosome", "--coverage_threshold", "5"],
    );
    assert_eq!(
        file_set(tmp.path()),
        file_set(&golden),
        "thr-split file set differs"
    );
    for name in file_set(&golden) {
        assert_eq!(
            std::fs::read(tmp.path().join(&name)).unwrap(),
            std::fs::read(golden.join(&name)).unwrap(),
            "thr-split file {name} differs"
        );
    }
}

#[test]
fn split_gzip_per_chr_decompresses_to_split_golden() {
    let golden = data_dir().join("phase_c/split");
    let tmp = run("split", &["--split_by_chromosome", "--gzip"]);
    for name in file_set(&golden) {
        if name.ends_with(".CpG_report.txt") {
            // Rust emits the gz variant; decompress and compare to the plain golden.
            let got = gunzip(&tmp.path().join(format!("{name}.gz")));
            let want = std::fs::read(golden.join(&name)).unwrap();
            assert_eq!(got, want, "split --gzip {name}.gz decompressed differs");
        } else {
            // Summary stays plain even under --gzip.
            assert_eq!(
                std::fs::read(tmp.path().join(&name)).unwrap(),
                std::fs::read(golden.join(&name)).unwrap(),
                "split --gzip summary {name} differs"
            );
        }
    }
}

#[test]
fn suffixed_output_split_doubles_suffix_and_matches_content() {
    // The extractor path: `-o foo.CpG_report.txt --split` → doubled-suffix names,
    // identical content to the bare-`-o` split golden.
    let golden = data_dir().join("phase_c/split");
    let tmp = run("foo.CpG_report.txt", &["--split_by_chromosome"]);
    let doubled = tmp.path().join("foo.CpG_report.txt.chrchr1.CpG_report.txt");
    assert!(doubled.exists(), "doubled-suffix split filename must exist");
    assert_eq!(
        std::fs::read(&doubled).unwrap(),
        std::fs::read(golden.join("split.chrchr1.CpG_report.txt")).unwrap(),
        "doubled-suffix split content must equal the split golden"
    );
}

// ── V12: split re-appearance truncates (mirror of Phase B's non-contiguous) ──

#[test]
fn split_reappearance_truncates_and_summary_in_last_chr() {
    let tmp = tempfile::tempdir().unwrap();
    let gdir = tmp.path().join("g");
    std::fs::create_dir(&gdir).unwrap();
    std::fs::write(gdir.join("g.fa"), ">chrA\nACGT\n>chrB\nACGT\n").unwrap();
    let cov = tmp.path().join("in.cov");
    // chrA p2=5, chrB p2=1, chrA p4=7 (re-appearance of chrA with a different pos).
    std::fs::write(
        &cov,
        "chrA\t2\t2\t100\t5\t0\nchrB\t2\t2\t100\t1\t0\nchrA\t4\t4\t100\t7\t0\n",
    )
    .unwrap();
    let out = tmp.path().join("out");
    std::fs::create_dir(&out).unwrap();
    Command::cargo_bin("coverage2cytosine_rs")
        .unwrap()
        .arg("-o")
        .arg("s")
        .arg("-g")
        .arg(&gdir)
        .arg("--dir")
        .arg(&out)
        .arg("--split_by_chromosome")
        .arg(&cov)
        .assert()
        .success();

    // chrA's file was truncated on reopen → only the 2nd block (pos4) coverage;
    // pos2 shows 0,0 (the first block's 5/0 was lost on the truncating reopen).
    let chra = std::fs::read_to_string(out.join("s.chrchrA.CpG_report.txt")).unwrap();
    assert!(
        chra.contains("chrA\t2\t+\t0\t0\tCG"),
        "pos2 must be 0,0 (truncated); got:\n{chra}"
    );
    assert!(
        !chra.contains("chrA\t2\t+\t5\t0"),
        "first-block 5/0 must be gone; got:\n{chra}"
    );

    // Full summary lands in chrA (last reopened), NOT chrB.
    assert!(
        !std::fs::read(out.join("s.chrchrA.cytosine_context_summary.txt"))
            .unwrap()
            .is_empty(),
        "chrA summary must be the full one (last reopened)"
    );
    assert!(
        std::fs::read(out.join("s.chrchrB.cytosine_context_summary.txt"))
            .unwrap()
            .is_empty(),
        "chrB summary must be empty"
    );
}
