//! Phase 2 byte-identity golden tests: `--drach` / `--m6A` (the standalone
//! DRACH-motif m6A report).
//!
//! Goldens in `tests/data/phase2_drach/gold/<mode>/` are the Perl v0.25.1 output
//! for each mode (regenerated by `tests/data/phase2_drach/generate_goldens.sh`).
//! Each test runs the Rust binary into a tempdir and compares the **file set**
//! and every file's bytes against the matching golden directory. `--gzip`
//! decompresses; `--zero_based` and `--CX` are compared directly against the
//! plain `--drach` golden (the DRACH path ignores both — early-exit / no `$zero`).
//!
//! Covers PLAN §9 V1–V16 (the integration cells; the CLI/`is_drach_motif` cells
//! V1/V2/V3 are unit-tested in `cli.rs`/`drach.rs`).

use std::io::Read;
use std::path::{Path, PathBuf};

use assert_cmd::Command;
use flate2::read::MultiGzDecoder;

fn d2() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/data/phase2_drach")
}
fn gold(mode: &str) -> PathBuf {
    d2().join("gold").join(mode)
}

fn gunzip(path: &Path) -> Vec<u8> {
    let mut d = MultiGzDecoder::new(std::fs::File::open(path).unwrap());
    let mut out = Vec::new();
    d.read_to_end(&mut out).unwrap();
    out
}

fn list_sorted(dir: &Path) -> Vec<String> {
    let mut v: Vec<String> = std::fs::read_dir(dir)
        .unwrap()
        .map(|e| e.unwrap().file_name().into_string().unwrap())
        .collect();
    v.sort();
    v
}

/// Run `coverage2cytosine_rs` into a fresh tempdir; assert success; return it.
fn run_rust(genome: &str, cov: &str, oname: &str, flags: &[&str]) -> tempfile::TempDir {
    let tmp = tempfile::tempdir().unwrap();
    Command::cargo_bin("coverage2cytosine")
        .unwrap()
        .arg("-o")
        .arg(oname)
        .arg("-g")
        .arg(d2().join(genome))
        .arg("--dir")
        .arg(tmp.path())
        .args(flags)
        .arg(d2().join(cov))
        .assert()
        .success();
    tmp
}

fn assert_dir_matches(rust_dir: &Path, mode: &str) {
    let g = gold(mode);
    assert_eq!(
        list_sorted(rust_dir),
        list_sorted(&g),
        "[{mode}] file-set mismatch"
    );
    for f in list_sorted(&g) {
        assert_eq!(
            std::fs::read(rust_dir.join(&f)).unwrap(),
            std::fs::read(g.join(&f)).unwrap(),
            "[{mode}] bytes differ in {f}"
        );
    }
}

/// `--gzip` Rust output vs a PLAIN golden dir: every file gains `.gz` and
/// decompresses byte-identically.
fn assert_gz_matches_plain(rust_dir: &Path, plain_mode: &str) {
    let g = gold(plain_mode);
    let gold_files = list_sorted(&g);
    let mut expected: Vec<String> = gold_files.iter().map(|f| format!("{f}.gz")).collect();
    expected.sort();
    assert_eq!(
        list_sorted(rust_dir),
        expected,
        "[{plain_mode}+gzip] file-set mismatch"
    );
    for f in &gold_files {
        assert_eq!(
            gunzip(&rust_dir.join(format!("{f}.gz"))),
            std::fs::read(g.join(f)).unwrap(),
            "[{plain_mode}+gzip] decompressed bytes differ in {f}"
        );
    }
}

#[test]
fn v5_top_strand_matches_perl() {
    let tmp = run_rust("g_top", "top.cov", "s", &["--drach"]);
    assert_dir_matches(tmp.path(), "top");
}

#[test]
fn v6_bottom_strand_matches_perl() {
    // The bottom-strand C is reported/looked-up at `pos-1` (the BS-seq anchor).
    let tmp = run_rust("g_bot", "bot.cov", "s", &["--drach"]);
    assert_dir_matches(tmp.path(), "bottom");
}

#[test]
fn v15_top_chromosome_start_wrap_emits() {
    // rev 2 A-F1 (the Critical): `ACAAA` cov@2 → `chrA 2 + 9 1 AA CAA` — the
    // wrapped `drach=substr(-2,5)="AA"`. Proves the top strand uses `perl_substr`.
    let tmp = run_rust("g_wrap", "wrap.cov", "s", &["--drach"]);
    assert_dir_matches(tmp.path(), "wrap");
}

#[test]
fn v10_bottom_truncated_5mer_emits() {
    // `AAAGTA` cov@4 → the 4-byte `drach` passes (pos-5 missing) + tri len≥3 → emits.
    let tmp = run_rust("g_trunc", "trunc.cov", "s", &["--drach"]);
    assert_dir_matches(tmp.path(), "trunc");
}

#[test]
fn v2_explicit_threshold_survives() {
    let tmp = run_rust(
        "g_top",
        "top.cov",
        "s",
        &["--drach", "--coverage_threshold", "5"],
    );
    assert_dir_matches(tmp.path(), "thr5");
}

#[test]
fn v4_raw_suffix_filename_not_stripped() {
    // `-o s.CpG_report.txt --drach` → `s.CpG_report.txt_DRACH_report.txt` (no strip).
    let tmp = run_rust("g_top", "top.cov", "s.CpG_report.txt", &["--drach"]);
    assert_dir_matches(tmp.path(), "rawsuffix");
}

#[test]
fn v12_split_by_chromosome_matches_perl() {
    let tmp = run_rust(
        "g_multi",
        "multi.cov",
        "s",
        &["--drach", "--split_by_chromosome"],
    );
    assert_dir_matches(tmp.path(), "split");
}

#[test]
fn v16_single_file_chromosome_ordering() {
    // Single-file, cov in non-sorted appearance order (chr2 before chr1) →
    // covered order = cov-appearance order.
    let tmp = run_rust("g_multi", "multi_rev.cov", "s", &["--drach"]);
    assert_dir_matches(tmp.path(), "single_order");
}

#[test]
fn v8_empty_cov_yields_empty_files() {
    // No `die` (unlike the core report); two 0-byte files, no panic.
    let tmp = run_rust("g_top", "empty.cov", "s", &["--drach"]);
    assert_dir_matches(tmp.path(), "empty");
}

#[test]
fn v11_gzip_decompresses_to_plain_golden() {
    let tmp = run_rust("g_top", "top.cov", "s", &["--drach", "--gzip"]);
    assert_gz_matches_plain(tmp.path(), "top");
}

#[test]
fn v13_zero_based_ignored() {
    // `--drach --zero_based` is byte-identical to `--drach` (no `$zero` branch).
    let tmp = run_rust("g_top", "top.cov", "s", &["--drach", "--zero_based"]);
    assert_dir_matches(tmp.path(), "top");
}

#[test]
fn v1_cx_early_exit_no_normal_report() {
    // `--drach --CX` ignores --CX (early-exit): the file set is exactly the DRACH
    // pair — NO `.CX_report.txt`, NO summary — byte-identical to plain `--drach`.
    let tmp = run_rust("g_top", "top.cov", "s", &["--drach", "--CX"]);
    assert_dir_matches(tmp.path(), "top");
}
