//! Phase 3 byte-identity golden tests: `--ffs` (tetra/penta/hexamer context
//! columns appended to each report line, 7 → 10 columns).
//!
//! Goldens in `tests/data/phase3_ffs/gold/<mode>/` are the Perl v0.25.1 output
//! for each mode (regenerated by `tests/data/phase3_ffs/generate_goldens.sh`).
//! Each test runs the Rust binary into a tempdir and compares the **file set**
//! and every file's bytes against the matching golden directory. `--gzip`
//! decompresses against the plain golden.
//!
//! Covers PLAN §9 V5–V16 (the integration cells; the offset-table cells V1–V4
//! are unit-tested on `ffs_fields` in `report.rs`, and V7 in `cli.rs`).

use std::io::Read;
use std::path::{Path, PathBuf};

use assert_cmd::Command;
use flate2::read::MultiGzDecoder;

fn d3() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/data/phase3_ffs")
}
fn gold(mode: &str) -> PathBuf {
    d3().join("gold").join(mode)
}

fn gunzip(path: &Path) -> Vec<u8> {
    let mut d = MultiGzDecoder::new(std::fs::File::open(path).unwrap());
    let mut out = Vec::new();
    d.read_to_end(&mut out).unwrap();
    out
}

fn list_sorted(dir: &Path) -> Vec<String> {
    let mut v: Vec<String> = std::fs::read_dir(dir)
        .unwrap()
        .map(|e| e.unwrap().file_name().into_string().unwrap())
        .collect();
    v.sort();
    v
}

fn run_rust(genome: &str, cov: &str, oname: &str, flags: &[&str]) -> tempfile::TempDir {
    let tmp = tempfile::tempdir().unwrap();
    Command::cargo_bin("coverage2cytosine_rs")
        .unwrap()
        .arg("-o")
        .arg(oname)
        .arg("-g")
        .arg(d3().join(genome))
        .arg("--dir")
        .arg(tmp.path())
        .args(flags)
        .arg(d3().join(cov))
        .assert()
        .success();
    tmp
}

fn assert_dir_matches(rust_dir: &Path, mode: &str) {
    let g = gold(mode);
    assert_eq!(
        list_sorted(rust_dir),
        list_sorted(&g),
        "[{mode}] file-set mismatch"
    );
    for f in list_sorted(&g) {
        assert_eq!(
            std::fs::read(rust_dir.join(&f)).unwrap(),
            std::fs::read(g.join(&f)).unwrap(),
            "[{mode}] bytes differ in {f}"
        );
    }
}

fn assert_gz_matches_plain(rust_dir: &Path, plain_mode: &str) {
    let g = gold(plain_mode);
    let gold_files = list_sorted(&g);
    // The summary stays plain; the report gains `.gz`.
    let mut expected: Vec<String> = gold_files
        .iter()
        .map(|f| {
            if f.ends_with(".cytosine_context_summary.txt") {
                f.clone()
            } else {
                format!("{f}.gz")
            }
        })
        .collect();
    expected.sort();
    assert_eq!(
        list_sorted(rust_dir),
        expected,
        "[{plain_mode}+gzip] file-set mismatch"
    );
    for f in &gold_files {
        let want = std::fs::read(g.join(f)).unwrap();
        let got = if f.ends_with(".cytosine_context_summary.txt") {
            std::fs::read(rust_dir.join(f)).unwrap()
        } else {
            gunzip(&rust_dir.join(format!("{f}.gz")))
        };
        assert_eq!(
            got, want,
            "[{plain_mode}+gzip] decompressed bytes differ in {f}"
        );
    }
}

#[test]
fn v8_ffs_cpg_matches_perl() {
    // 10-col CpG report (cols 1–7 unchanged + tetra/penta/hexa). Includes the
    // uncovered chrC 10-col `0 0` line (V13) and the forward-hexa negative-wrap.
    let tmp = run_rust("g_main", "main.cov", "s", &["--ffs"]);
    assert_dir_matches(tmp.path(), "ffs_cpg");
}

#[test]
fn v9_ffs_cx_matches_perl() {
    let tmp = run_rust("g_main", "main.cov", "s", &["--ffs", "--CX"]);
    assert_dir_matches(tmp.path(), "ffs_cx");
}

#[test]
fn v10_ffs_zero_based_shifts_pos_but_not_context_columns() {
    // The core report's pos shifts under --zero_based; the 3 context columns are
    // coordinate-invariant (extracted from the genome). Whole-dir match + the
    // context-column invariant vs the 1-based ffs_cpg golden.
    let tmp = run_rust("g_main", "main.cov", "s", &["--ffs", "--zero_based"]);
    assert_dir_matches(tmp.path(), "ffs_zero");
    // V10 discriminator: cols 8–10 (the last 3) of each report line are identical
    // between the zero-based and 1-based goldens, while col 2 (pos) differs.
    let ctx = |dir: &str| -> Vec<String> {
        let body = std::fs::read_to_string(gold(dir).join("s.CpG_report.txt")).unwrap();
        body.lines()
            .map(|l| {
                let f: Vec<&str> = l.split('\t').collect();
                format!("{}\t{}\t{}", f[7], f[8], f[9]) // tetra/penta/hexa
            })
            .collect()
    };
    assert_eq!(
        ctx("ffs_zero"),
        ctx("ffs_cpg"),
        "context columns must be frozen"
    );
}

#[test]
fn v11_ffs_split_matches_perl() {
    let tmp = run_rust(
        "g_main",
        "main.cov",
        "s",
        &["--ffs", "--split_by_chromosome"],
    );
    assert_dir_matches(tmp.path(), "ffs_split");
}

#[test]
fn v12_ffs_gzip_decompresses_to_plain_golden() {
    let tmp = run_rust("g_main", "main.cov", "s", &["--ffs", "--gzip"]);
    assert_gz_matches_plain(tmp.path(), "ffs_cpg");
}

#[test]
fn v6_ffs_merge_cov_unchanged_by_ffs() {
    // `--ffs --merge_CpGs`: the 10-col report merges into a merged cov that is
    // byte-identical to a no-ffs run (the merge re-read discards the extra cols).
    let tmp = run_rust("g_merge", "merge.cov", "s", &["--ffs", "--merge_CpGs"]);
    assert_dir_matches(tmp.path(), "ffs_merge");
    // The ffs and no-ffs merged-cov files are byte-identical.
    assert_eq!(
        std::fs::read(gold("ffs_merge").join("s.CpG_report.merged_CpG_evidence.cov")).unwrap(),
        std::fs::read(gold("plain_merge").join("s.CpG_report.merged_CpG_evidence.cov")).unwrap(),
        "merge must discard the ffs columns → identical merged cov",
    );
}

#[test]
fn v5_ffs_does_not_change_the_context_summary() {
    // The cytosine-context summary is fed tri+upstream only — `--ffs` leaves it
    // byte-identical to a no-ffs run (compared on the RUST output).
    let ffs = run_rust("g_main", "main.cov", "s", &["--ffs"]);
    let plain = run_rust("g_main", "main.cov", "s", &[]);
    assert_eq!(
        std::fs::read(ffs.path().join("s.cytosine_context_summary.txt")).unwrap(),
        std::fs::read(plain.path().join("s.cytosine_context_summary.txt")).unwrap(),
    );
}

#[test]
fn v13_uncovered_chromosome_emits_10col_zero_lines() {
    // chrC is uncovered in main.cov; at the default threshold 0 it still emits
    // 10-col `0 0` ffs lines (verified within the ffs_cpg golden).
    let body = std::fs::read_to_string(gold("ffs_cpg").join("s.CpG_report.txt")).unwrap();
    let chrc: Vec<&str> = body.lines().filter(|l| l.starts_with("chrC\t")).collect();
    assert!(!chrc.is_empty(), "chrC (uncovered) must emit lines");
    for l in chrc {
        assert_eq!(
            l.split('\t').count(),
            10,
            "uncovered line must be 10-col: {l}"
        );
        assert!(l.contains("\t0\t0\t"), "uncovered line must be 0 0: {l}");
    }
}

#[test]
fn v17_ffs_nome_seq_suppresses_the_nome_cov_companion() {
    // --ffs × --nome-seq interaction (Phase-3 dual-review Critical): under --ffs,
    // Perl's `$tetra` branch short-circuits before `print CYTCOV`, so the
    // `.NOMe.CpG.cov` is opened (because $nome) but never written → 0-byte. The
    // NOMe core REPORT is still the 10-col ffs line (ACG/TCG-filtered).
    let tmp = run_rust("g_nome", "nome.cov", "s", &["--ffs", "--nome-seq"]);
    assert_dir_matches(tmp.path(), "ffs_nome");
    // Pin the suppression explicitly: the cov companion is present but empty.
    let cov = tmp.path().join("s.NOMe.CpG.cov");
    assert!(cov.exists(), "the .NOMe.CpG.cov file is still created");
    assert_eq!(
        std::fs::metadata(&cov).unwrap().len(),
        0,
        "but must be 0 bytes under --ffs"
    );
    // The NOMe core report IS still emitted (10-col ffs lines).
    let report = std::fs::read_to_string(tmp.path().join("s.NOMe.CpG_report.txt")).unwrap();
    assert!(
        report
            .lines()
            .next()
            .is_some_and(|l| l.split('\t').count() == 10),
        "the NOMe core report must still be 10-col under --ffs",
    );
}

#[test]
fn v15_n_window_emitted_verbatim_not_filtered() {
    // Perl does NOT filter N-containing windows (the `--help` "Ns ignored" claim
    // is stale) — the tetra/penta/hexa fields carry N through verbatim.
    let tmp = run_rust("g_nwin", "nwin.cov", "s", &["--ffs", "--CX"]);
    assert_dir_matches(tmp.path(), "ffs_nwin");
    // Sanity: the golden actually contains an N inside a context column.
    let body = std::fs::read_to_string(gold("ffs_nwin").join("s.CX_report.txt")).unwrap();
    assert!(
        body.lines().any(|l| {
            let f: Vec<&str> = l.split('\t').collect();
            f.len() == 10 && (f[7].contains('N') || f[8].contains('N') || f[9].contains('N'))
        }),
        "expected an N inside a tetra/penta/hexa field"
    );
}
