//! Hermetic byte-identity gate for `filter_non_conversion_rs`.
//!
//! For every success case in `tests/data/cases.tsv` (each generated by the
//! REAL Perl `filter_non_conversion` v0.25.1 via `generate_goldens.sh`), this
//! test runs the Rust binary on the committed input BAM and asserts:
//! - `samtools view` of the Rust `.nonCG_filtered.bam` byte-equals the
//!   committed `exp_filtered.sam` (Perl's filtered body — same records, order,
//!   tags; SPEC §8 D1: body-only, header excluded);
//! - same for `.nonCG_removed_seqs.bam` vs `exp_removed.sam`;
//! - the `.non-conversion_filtering.txt` report byte-equals Perl's, after
//!   normalizing the non-deterministic run-time line (SPEC D2).
//!
//! Renders the Rust output with `samtools` (matching the spike methodology).
//! If `samtools` is not on PATH, the test SKIPs (prints + returns success) so
//! CI without samtools sees no false failure. Perl is NOT needed at test time
//! (goldens are committed).

use std::path::{Path, PathBuf};
use std::process::Command as StdCommand;

use assert_cmd::Command as AssertCommand;
use tempfile::TempDir;

fn data_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/data")
}

fn samtools_available() -> bool {
    StdCommand::new("samtools")
        .arg("--version")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

/// `samtools view <bam>` (body only, no header) → raw bytes.
fn samtools_view_body(bam: &Path) -> Vec<u8> {
    let out = StdCommand::new("samtools")
        .arg("view")
        .arg(bam)
        .output()
        .expect("samtools view failed to spawn");
    assert!(
        out.status.success(),
        "samtools view {} failed: {}",
        bam.display(),
        String::from_utf8_lossy(&out.stderr)
    );
    out.stdout
}

/// Strip the final `filter_non_conversion completed in …` run-time line for
/// the deterministic comparison (SPEC D2).
fn strip_timing(s: &str) -> &str {
    match s.find("filter_non_conversion completed in") {
        Some(i) => &s[..i],
        None => s,
    }
}

/// Drop the trailing `.bam` (dot-anchored), matching the Rust/Perl naming.
fn stem(inbase: &str) -> &str {
    inbase.strip_suffix(".bam").unwrap_or(inbase)
}

struct Case {
    name: String,
    inbase: String,
    flags: Vec<String>,
}

fn read_cases(tsv: &Path) -> Vec<Case> {
    let text = std::fs::read_to_string(tsv).expect("read cases.tsv");
    text.lines()
        .filter(|l| !l.trim().is_empty())
        .map(|line| {
            let mut it = line.split('\t');
            let name = it.next().unwrap_or("").to_string();
            let inbase = it.next().unwrap_or("").to_string();
            let flags_str = it.next().unwrap_or("");
            let flags = flags_str
                .split_whitespace()
                .map(str::to_string)
                .collect::<Vec<_>>();
            Case {
                name,
                inbase,
                flags,
            }
        })
        .collect()
}

fn run_case(data: &Path, case: &Case) {
    let case_dir = data.join(&case.name);
    let tmp = TempDir::new().expect("tmp dir");

    // Copy the committed input next to where the binary will write outputs,
    // and run from there with the basename so the report echoes the same path
    // string the Perl baseline used.
    std::fs::copy(case_dir.join(&case.inbase), tmp.path().join(&case.inbase))
        .expect("copy input bam");

    let mut cmd = AssertCommand::cargo_bin("filter_non_conversion_rs").unwrap();
    cmd.current_dir(tmp.path());
    for f in &case.flags {
        cmd.arg(f);
    }
    cmd.arg(&case.inbase).assert().success();

    let st = stem(&case.inbase);

    // 1. Filtered (kept) body.
    let rust_filtered = samtools_view_body(&tmp.path().join(format!("{st}.nonCG_filtered.bam")));
    let exp_filtered = std::fs::read(case_dir.join("exp_filtered.sam")).expect("read exp_filtered");
    assert_eq!(
        rust_filtered, exp_filtered,
        "[{}] filtered (kept) body differs from Perl golden",
        case.name
    );

    // 2. Removed body.
    let rust_removed = samtools_view_body(&tmp.path().join(format!("{st}.nonCG_removed_seqs.bam")));
    let exp_removed = std::fs::read(case_dir.join("exp_removed.sam")).expect("read exp_removed");
    assert_eq!(
        rust_removed, exp_removed,
        "[{}] removed body differs from Perl golden",
        case.name
    );

    // 3. Report (normalize the non-deterministic run-time line).
    let rust_report = std::fs::read_to_string(
        tmp.path()
            .join(format!("{st}.non-conversion_filtering.txt")),
    )
    .expect("read rust report");
    let exp_report =
        std::fs::read_to_string(case_dir.join("exp_report.txt")).expect("read exp report");
    assert_eq!(
        strip_timing(&rust_report),
        strip_timing(&exp_report),
        "[{}] report (pre-timing) differs from Perl golden",
        case.name
    );
    // The Rust report must carry a well-formed run-time line (it is the only /
    // last file, so it always gets one).
    assert!(
        rust_report.contains("filter_non_conversion completed in ")
            && rust_report.trim_end().ends_with('s'),
        "[{}] report missing a well-formed run-time line: {rust_report:?}",
        case.name
    );
}

#[test]
fn byte_identity_against_perl_goldens() {
    if !samtools_available() {
        eprintln!("SKIP: samtools not on PATH — byte-identity gate needs it to render Rust output");
        return;
    }
    let data = data_dir();
    let cases = read_cases(&data.join("cases.tsv"));
    assert!(
        !cases.is_empty(),
        "cases.tsv is empty — run generate_goldens.sh"
    );
    for case in &cases {
        run_case(&data, case);
    }
    eprintln!("byte-identity gate PASSED for {} cases", cases.len());
}
