# This is a basic workflow to ensure the Bismark tools are working

name: Bismark CI workflow

# Controls when the action will run. Triggers the workflow on push or pull request events but only for the master branch
on:
  pull_request:
  push:
    branches: 
      - master
      - devel
    # branches: [ master, devel ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "BuildBismark"
  BuildBismark:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello World, this is my action!"
    
    - name: Bismark Help
      run: $GITHUB_WORKSPACE/bismark --help
    
      # Runs a set of commands using the runners shell
    - name: Install dependencies
      run: |
        sudo apt-get install libgd-perl
        sudo cpan App::cpanminus
        sudo cpanm GD::Graph
        wget https://sourceforge.net/projects/bowtie-bio/files/latest/download
        unzip download
        ln -s bowtie2*/bowtie2 .
        
    - name: software versions
      run:
        $GITHUB_WORKSPACE/bismark --version
        $GITHUB_WORKSPACE/bowtie2 --version
       
     
    
